# Generated by Django 2.1.7 on 2020-01-06 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chantier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_of_work', models.DateField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('main_picture', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.BinaryField()),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chantier.Chantier')),
            ],
        ),
    ]
