# Generated by Django 2.1.7 on 2020-01-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chantier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chantier',
            name='main_picture',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
