# Generated by Django 2.1.7 on 2020-01-06 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chantier', '0002_auto_20200106_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chantier',
            name='main_picture',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='chantier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='chantier.Chantier'),
        ),
    ]
