# Generated by Django 2.1.7 on 2020-01-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chantier', '0003_auto_20200106_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chantier',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
