# Generated by Django 2.1.7 on 2020-06-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chantier', '0004_auto_20200107_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='thumbnails/'),
        ),
    ]
