# syntax=docker/dockerfile:1
FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY requirements.txt ./
RUN pip install --upgrade pip && pip install -r requirements.txt && pip install gunicorn

COPY . .

RUN python webCarpentry/manage.py collectstatic --noinput

EXPOSE 8000

CMD ["gunicorn", "webCarpentry.wsgi:application", "--bind", "0.0.0.0:8000"]
