# syntax=docker/dockerfile:1
FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY webCarpentry/requirements.txt ./
RUN pip install --upgrade pip && pip install -r requirements.txt

# Install dev dependencies (if any)
# RUN pip install debugpy

COPY . .

EXPOSE 8000

CMD ["python", "webCarpentry/manage.py", "runserver", "0.0.0.0:8000"]
