# Generated by Django 2.1.5 on 2019-02-09 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('logo', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Chantier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('short_description', models.CharField(max_length=250)),
                ('localisation', models.CharField(max_length=100)),
                ('date_of_chantier', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChantierAsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arboressence.Category')),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arboressence.Chantier')),
            ],
        ),
        migrations.CreateModel(
            name='ChantierAsEssence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arboressence.Chantier')),
            ],
        ),
        migrations.CreateModel(
            name='Essences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_photo', models.BinaryField()),
                ('thumbnail_photo', models.BinaryField()),
                ('InSerieNumber', models.IntegerField()),
                ('chantier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arboressence.Chantier')),
            ],
        ),
        migrations.AddField(
            model_name='chantierasessence',
            name='essence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arboressence.Essences'),
        ),
    ]
