# Generated by Django 2.1.5 on 2019-02-09 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arboressence', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chantierascategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='chantierascategory',
            name='chantier',
        ),
        migrations.RemoveField(
            model_name='chantierasessence',
            name='chantier',
        ),
        migrations.RemoveField(
            model_name='chantierasessence',
            name='essence',
        ),
        migrations.AddField(
            model_name='category',
            name='chantier',
            field=models.ManyToManyField(to='arboressence.Chantier'),
        ),
        migrations.AddField(
            model_name='essences',
            name='chantier',
            field=models.ManyToManyField(to='arboressence.Chantier'),
        ),
        migrations.DeleteModel(
            name='ChantierAsCategory',
        ),
        migrations.DeleteModel(
            name='ChantierAsEssence',
        ),
    ]
