# Generated by Django 2.1.5 on 2019-02-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arboressence', '0002_auto_20190209_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='chantier',
        ),
        migrations.RemoveField(
            model_name='essences',
            name='chantier',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='chantier',
        ),
        migrations.AddField(
            model_name='chantier',
            name='category',
            field=models.ManyToManyField(to='arboressence.Category'),
        ),
        migrations.AddField(
            model_name='chantier',
            name='essence',
            field=models.ManyToManyField(to='arboressence.Essences'),
        ),
        migrations.AddField(
            model_name='chantier',
            name='photo',
            field=models.ManyToManyField(to='arboressence.Photo'),
        ),
    ]
